services:
  django-web:
    build: ./app
    container_name: django-web
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/staticfiles
      - ./app:/app # Autoload code changes in the container
      - django-venv:/app/.venv # Named volume

    environment:
      - UV_CACHE_DIR=/tmp/uv-cache # Cache in /tmp for development
      - PYTHONUNBUFFERED=1 # Disable Python output buffering for real-time logs
    env_file:
      - .env.local
    depends_on:
      - mysql
    command: uv run manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment â€” it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static:/static
    depends_on:
      - django-web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email davi9898@gmail.com -d paper-snitch.ing.unimore.it --agree-tos

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/.client.cnf:/root/.my.cnf
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env.local
volumes:
  django-venv:
